version: '3.9'

services:
  tikz-app:
    build: .
    ports:
      - '5173:5173'
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=3001
      - NODE_ENV=development
